### ISSUE TITLE
Array to Object

### ISSUE THREAD

**Issue by echo-youn** [Ella-kim-bee/picker#2]
https://github.com/Ella-kim-bee/picker/blob/a1724f219ab9057d2b1689caf3b7a70bb704a5f0/index.html#L886-L891

`{
image: "images/img_index_weekly_tooltip_eyebrow.jpg",
alt: "shuuemura eyebrow",
brandName: "shu uemura",
productName:"하드 포뮬라 - 스톤 그레이",
iframe: "picker/eyebrow#shuuemura.html"
}`

**Comment by Ella-kim-bee** [comment]
수정완료했습니다
